branch-defaults:
  default:
    environment: django-env1
    group_suffix: null
environment-defaults:
  django-env1:
    branch: null
    repository: null
global:
  application_name: django-tutorial
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.8
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
platform: Python 3.8 running on 64bit Amazon Linux 2
